"use client";
import {useEffect,useMemo,useState} from "react";
import {createClient,type SupabaseClient} from "@supabase/supabase-js";
type Appointment={id:string;patient_name:string;patient_phone:string|null;specialty:string;appointment_at:string;consultation_price:number;paid_amount:number;status:string;unit_id:string;clinic_units:{name:string}|null};
const url=process.env.NEXT_PUBLIC_SUPABASE_URL;
const key=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;
const supabase:SupabaseClient|null=url&&key?createClient(url,key):null;
const states:Record<string,string>={pending:"Pendente",contacted:"Contatado",rescheduled:"Reagendado",attended:"Compareceu",no_response:"Sem resposta",opted_out:"Não deseja contato"};
const menu=[["Dashboard","▦"],["Faltosos","☷"],["Contatos","◉"],["Reagendamentos","↗"],["Financeiro","◈"]] as const;
const money=(n:number)=>n.toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const date=(s:string)=>new Date(s).toLocaleDateString("pt-BR",{timeZone:"UTC"});
function Icon({name,size=20}:{name:string;size?:number}){const paths:Record<string,React.ReactNode>={grid:<><rect x="3" y="3" width="7" height="7" rx="1.5"/><rect x="14" y="3" width="7" height="7" rx="1.5"/><rect x="3" y="14" width="7" height="7" rx="1.5"/><rect x="14" y="14" width="7" height="7" rx="1.5"/></>,users:<><path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M22 21v-2a4 4 0 0 0-3-3.87M16 3.13a4 4 0 0 1 0 7.75"/></>,phone:<><path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.8 19.8 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6A19.8 19.8 0 0 1 2.12 4.2 2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72c.12.96.35 1.9.68 2.79a2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.25a2 2 0 0 1 2.11-.45c.89.33 1.83.56 2.79.68A2 2 0 0 1 22 16.92Z"/></>,calendar:<><rect x="3" y="5" width="18" height="16" rx="2"/><path d="M16 3v4M8 3v4M3 10h18"/></>,wallet:<><rect x="2" y="5" width="20" height="16" rx="2"/><path d="M2 9h20M16 15h2"/></>,search:<><circle cx="11" cy="11" r="8"/><path d="m21 21-4.35-4.35"/></>,logout:<><path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4M16 17l5-5-5-5M21 12H9"/></>,arrow:<><path d="M7 17 17 7M7 7h10v10"/></>,shield:<><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10Z"/><path d="m9 12 2 2 4-4"/></>,filter:<><path d="M4 7h16M7 12h10M10 17h4"/></>,menu:<><path d="M4 6h16M4 12h16M4 18h16"/></>,close:<><path d="M18 6 6 18M6 6l12 12"/></>,activity:<><path d="M3 12h4l3-8 4 16 3-8h4"/></>,check:<><path d="m5 12 4 4L19 6"/></>,clock:<><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/></>,spark:<><path d="m12 3 1.8 6.2L20 11l-6.2 1.8L12 19l-1.8-6.2L4 11l6.2-1.8L12 3Z"/></>};return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[name]??paths.grid}</svg>}
export default function Home(){
 const [user,setUser]=useState<string|null>(null),[loading,setLoading]=useState(true),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[message,setMessage]=useState(""),[profile,setProfile]=useState<{display_name:string;role:string;active:boolean}|null>(null),[rows,setRows]=useState<Appointment[]>([]),[unit,setUnit]=useState("Todas"),[tab,setTab]=useState("Dashboard"),[search,setSearch]=useState(""),[busy,setBusy]=useState(false),[mobile,setMobile]=useState(false),[statusFilter,setStatusFilter]=useState("Todos");
 useEffect(()=>{if(!supabase){setLoading(false);return}const client=supabase;client.auth.getUser().then(({data})=>{setUser(data.user?.id??null);setLoading(false)});const {data:{subscription}}=client.auth.onAuthStateChange((_event,session)=>{setUser(session?.user?.id??null)});return()=>subscription.unsubscribe()},[]);
 useEffect(()=>{if(!supabase||!user){setProfile(null);setRows([]);return}const client=supabase;client.from("operator_profiles").select("display_name,role,active").eq("user_id",user).maybeSingle().then(({data,error})=>{if(error)setMessage("Não foi possível validar as permissões.");setProfile(data)});client.from("missed_appointments").select("id,patient_name,patient_phone,specialty,appointment_at,consultation_price,paid_amount,status,unit_id,clinic_units(name)").order("appointment_at",{ascending:false}).limit(500).then(({data,error})=>{if(error)setMessage(error.message);else setRows((data??[]) as unknown as Appointment[])})},[user]);
 const filtered=useMemo(()=>rows.filter(r=>(unit==="Todas"||r.clinic_units?.name===unit)&&((r.patient_name+" "+r.specialty+" "+(r.clinic_units?.name??"")).toLowerCase().includes(search.toLowerCase()))),[rows,unit,search]);
 const visible=useMemo(()=>filtered.filter(r=>(statusFilter==="Todos"||r.status===statusFilter)&&(tab!=="Reagendamentos"||["rescheduled","attended"].includes(r.status))&&(tab!=="Contatos"||["contacted","rescheduled","attended","no_response","opted_out"].includes(r.status))),[filtered,statusFilter,tab]);
 const contacted=filtered.filter(r=>["contacted","rescheduled","attended"].includes(r.status)).length;
 const recovered=filtered.filter(r=>["rescheduled","attended"].includes(r.status)).length;
 const paid=filtered.reduce((s,r)=>s+Number(r.paid_amount||0),0);
 const potential=filtered.reduce((s,r)=>s+Number(r.consultation_price||0),0);
 const pct=filtered.length?Math.round(recovered/filtered.length*100):0;
 const stages=[{label:"Pendentes",count:filtered.filter(r=>r.status==="pending").length,color:"#e6ad5b"},{label:"Contatados",count:contacted,color:"#54a8a0"},{label:"Reagendados",count:recovered,color:"#207b67"},{label:"Sem resposta",count:filtered.filter(r=>r.status==="no_response").length,color:"#91a6b5"}];
 const units=[...new Set(rows.map(r=>r.clinic_units?.name).filter((s):s is string=>Boolean(s)))];
 async function login(e:React.FormEvent){e.preventDefault();if(!supabase)return;setBusy(true);setMessage("");const {error}=await supabase.auth.signInWithPassword({email,password});if(error)setMessage("Não foi possível entrar. Confira suas credenciais.");setBusy(false)}
 async function update(r:Appointment,status:string){if(!supabase)return;const {error}=await supabase.from("missed_appointments").update({status}).eq("id",r.id);if(error){setMessage("Não foi possível atualizar o registro.");return}setRows(prev=>prev.map(p=>p.id===r.id?{...p,status}:p))}
 async function whatsapp(r:Appointment){if(!supabase||!r.patient_phone||r.status==="opted_out")return;const phone=r.patient_phone.replace(/\D/g,"");if(!phone){setMessage("Número de telefone inválido.");return}const msg="Olá! Aqui é da Rede Mais Saúde. Gostaríamos de saber se deseja ajuda para reagendar seu atendimento. Podemos conversar?";const link="https://wa.me/"+phone+"?text="+encodeURIComponent(msg);const win=window.open(link,"_blank","noopener,noreferrer");if(!win){setMessage("O navegador bloqueou a abertura do WhatsApp. Habilite pop-ups e tente novamente.");return}const {error}=await supabase.from("contact_events").insert({appointment_id:r.id,operator_id:user,outcome:"whatsapp_opened"});if(error)setMessage("WhatsApp aberto, mas não foi possível registrar o evento.")}
 const switchTab=(t:string)=>{setTab(t);setMobile(false);setStatusFilter("Todos")};
 if(loading)return <main className="loading-screen"><div className="loading-logo">+</div><h2>Preparando sua central...</h2></main>;
 if(!supabase)return <main className="loading-screen"><h2>Configuração pendente</h2><p>Variáveis públicas do Supabase não configuradas na Vercel.</p></main>;
 const client=supabase;
 if(!user)return <main className="login-page"><div className="login-ambient"/><section className="login-card"><div className="login-symbol">+</div><div className="eyebrow">PLATAFORMA DE GESTÃO</div><h1>Bem-vindo à sua<br/><em>central de recuperação.</em></h1><p className="muted">Acesse sua área segura da Rede Mais Saúde.</p><form onSubmit={login} className="login-form"><label>E-mail institucional<input required type="email" autoComplete="username" placeholder="seuemail@empresa.com" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Senha<input required type="password" autoComplete="current-password" placeholder="Sua senha" value={password} onChange={e=>setPassword(e.target.value)}/></label><button className="primary-btn" disabled={busy}>{busy?"Entrando...":"Acessar plataforma"} <Icon name="arrow" size={17}/></button></form>{message&&<p className="notice" role="alert">{message}</p>}<div className="login-footer"><Icon name="shield" size={16}/> Ambiente protegido · Acesso restrito</div></section><div className="login-side"><div className="login-side-content"><span className="eyebrow light">REDE MAIS SAÚDE</span><h2>Cuidar também é<br/>reconectar.</h2><p>Mais clareza para sua operação. Mais oportunidades para acolher seus pacientes.</p><div className="login-line"/></div></div></main>;
 if(!profile?.active)return <main className="login-page"><section className="login-card"><div className="login-symbol">+</div><h1>Acesso aguardando autorização</h1><p className="muted">Sua conta está autenticada, mas ainda não possui um perfil de operador ativo.</p><button className="primary-btn" onClick={()=>client.auth.signOut()}>Sair</button></section></main>;
 return <div className="app-shell">
 {mobile&&<button className="mobile-backdrop" aria-label="Fechar menu" onClick={()=>setMobile(false)}/>}
 <aside className={"sidebar "+(mobile?"sidebar-open":"")}><div className="brand-row"><div className="brand-symbol">+</div><div><strong>Rede Mais Saúde</strong><small>Central de Recuperação</small></div></div><div className="side-divider"/><div className="side-caption">ESPAÇO DE TRABALHO</div><nav className="side-nav" aria-label="Navegação principal">{menu.map(([s])=><button key={s} className={tab===s?"selected":""} onClick={()=>switchTab(s)}><Icon name={s==="Dashboard"?"grid":s==="Faltosos"?"users":s==="Contatos"?"phone":s==="Reagendamentos"?"calendar":"wallet"} size={19}/><span>{s}</span>{tab===s&&<span className="nav-indicator"/>}</button>)}</nav><div className="sidebar-bottom"><div className="security-card"><Icon name="shield" size={19}/><div><strong>Ambiente seguro</strong><span>Dados protegidos por unidade</span></div></div><div className="account-row"><div className="avatar">{(profile.display_name||"A").charAt(0).toUpperCase()}</div><div className="account-copy"><strong>{profile.display_name||"Operador"}</strong><small>{profile.role==="admin"?"Administrador":"Operador"}</small></div><button className="icon-button logout-btn" title="Sair" aria-label="Sair da conta" onClick={()=>client.auth.signOut()}><Icon name="logout" size={18}/></button></div></div></aside>
 <div className="workspace"><header className="app-header"><div className="header-left"><button className="mobile-menu icon-button" aria-label="Abrir menu" onClick={()=>setMobile(true)}><Icon name="menu"/></button><span className="breadcrumb">Central de Recuperação</span><span className="breadcrumb-sep">/</span><strong>{tab}</strong></div><div className="header-right"><span className="live-dot"/> <span>Ambiente conectado</span><div className="header-avatar">{(profile.display_name||"A").charAt(0).toUpperCase()}</div></div></header>
 <main className="content"><div className="heading-row"><div><div className="eyebrow">VISÃO GERAL DA OPERAÇÃO</div><h1>{tab==="Dashboard"?"Visão geral":tab}</h1><p className="page-description">{tab==="Dashboard"?"Acompanhe seus indicadores e oportunidades de recuperação em um só lugar.":tab==="Financeiro"?"Acompanhe os valores registrados e o potencial de recuperação.":tab==="Reagendamentos"?"Visualize os pacientes que voltaram à jornada de cuidado.":tab==="Contatos"?"Acompanhe o histórico de tentativas e o andamento dos contatos.":"Gerencie os pacientes que não compareceram aos atendimentos."}</p></div><div className="date-pill"><Icon name="calendar" size={17}/>{new Date().toLocaleDateString("pt-BR",{day:"2-digit",month:"long",year:"numeric"})}</div></div>
 {message&&<div className="notice" role="alert">{message}<button aria-label="Fechar aviso" onClick={()=>setMessage("")}><Icon name="close" size={16}/></button></div>}
 <section className="filter-bar" aria-label="Filtros"><div className="filter-heading"><Icon name="filter" size={18}/><strong>Filtros</strong></div><label className="filter-select"><span>Unidade</span><select value={unit} onChange={e=>setUnit(e.target.value)}><option value="Todas">Todas as unidades</option>{units.map(u=><option key={u} value={u}>{u}</option>)}</select></label><label className="filter-search"><Icon name="search" size={18}/><input placeholder="Buscar paciente ou especialidade..." aria-label="Buscar paciente ou especialidade" value={search} onChange={e=>setSearch(e.target.value)}/></label></section>
 <div className="metric-grid"><div className="metric-card"><div className="metric-head"><span>Total de faltosos</span><div className="metric-icon blue"><Icon name="users"/></div></div><strong className="metric-value">{filtered.length}</strong><div className="metric-foot">Registros no período disponível</div></div><div className="metric-card"><div className="metric-head"><span>Pacientes contatados</span><div className="metric-icon teal"><Icon name="phone"/></div></div><strong className="metric-value">{contacted}</strong><div className="metric-foot">Contato ou recuperação registrada</div></div><div className="metric-card"><div className="metric-head"><span>Reagendados</span><div className="metric-icon green"><Icon name="calendar"/></div></div><strong className="metric-value">{recovered}</strong><div className="metric-foot"><span className="metric-highlight">{pct}%</span> dos faltosos registrados</div></div><div className="metric-card"><div className="metric-head"><span>Valor registrado como pago*</span><div className="metric-icon gold"><Icon name="wallet"/></div></div><strong className="metric-value money-value">{money(paid)}</strong><div className="metric-foot">Sem confirmação financeira automática</div></div></div>
 <div className="insights-grid"><section className="surface insight-panel"><div className="section-title"><div><span className="eyebrow">DESEMPENHO</span><h2>Funil de recuperação</h2></div><div className="section-icon"><Icon name="activity" size={19}/></div></div><p className="panel-description">Distribuição dos registros por etapa de atendimento.</p><div className="funnel">{stages.map(s=><div className="funnel-row" key={s.label}><div className="funnel-label"><span>{s.label}</span><strong>{s.count}</strong></div><div className="funnel-track"><div className="funnel-fill" style={{width:(filtered.length?s.count/filtered.length*100:0)+"%",background:s.color}}/></div></div>)}</div><div className="insight-foot"><Icon name="spark" size={16}/>{filtered.length?"Indicadores calculados a partir dos registros disponíveis.":"Os gráficos serão preenchidos quando houver registros."}</div></section><section className="surface recovery-panel"><div className="section-title"><div><span className="eyebrow">OPORTUNIDADE</span><h2>Potencial de recuperação</h2></div><div className="section-icon"><Icon name="arrow" size={19}/></div></div><p className="panel-description">Estimativa com base nos valores de consulta cadastrados.</p><div className="recovery-ring" style={{background:"conic-gradient(#218875 "+pct+"%, #eaf0ed 0)"}}><div><strong>{pct}%</strong><span>Reagendados</span></div></div><div className="recovery-stats"><div><span>Valor potencial</span><strong>{money(potential)}</strong></div><div><span>Valor pago registrado*</span><strong>{money(paid)}</strong></div></div></section></div>
 <section className="surface patient-panel"><div className="patient-head"><div><span className="eyebrow">ACOMPANHAMENTO</span><h2>{tab==="Reagendamentos"?"Pacientes reagendados":tab==="Contatos"?"Contatos registrados":"Lista de atendimentos"}</h2><p className="panel-description">Gerencie os registros e acompanhe cada etapa do atendimento.</p></div><div className="patient-controls"><select aria-label="Filtrar por status" value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="Todos">Todos os status</option>{Object.entries(states).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><span className="count-pill">{visible.length} registros</span></div></div><div className="table-scroll"><table className="patient-table"><thead><tr><th>PACIENTE</th><th>UNIDADE / ESPECIALIDADE</th><th>DATA</th><th>VALOR</th><th>STATUS</th><th>AÇÃO</th></tr></thead><tbody>{visible.map(r=><tr key={r.id}><td><div className="patient-name"><div className="patient-avatar">{r.patient_name.charAt(0).toUpperCase()}</div><strong>{r.patient_name}</strong></div></td><td><strong className="unit-name">{r.clinic_units?.name??"—"}</strong><small className="specialty">{r.specialty}</small></td><td className="nowrap">{date(r.appointment_at)}</td><td className="nowrap">{money(Number(r.consultation_price||0))}</td><td><select className={"status-select status-"+r.status} aria-label={"Status de "+r.patient_name} value={r.status} onChange={e=>update(r,e.target.value)}>{Object.entries(states).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></td><td><button className="whatsapp-btn" disabled={!r.patient_phone||r.status==="opted_out"} onClick={()=>whatsapp(r)}><Icon name="phone" size={15}/> WhatsApp</button></td></tr>)}</tbody></table></div>{visible.length===0&&<div className="empty-state"><div className="empty-icon"><Icon name="users" size={26}/></div><h3>Nenhum atendimento encontrado</h3><p>{rows.length===0?"Ainda não há pacientes importados. A integração com a API de agendamentos está pendente.":"Tente ajustar os filtros para encontrar outros registros."}</p></div>}<div className="table-footer"><span>Exibindo {visible.length} de {filtered.length} registros filtrados</span><span><Icon name="shield" size={14}/> Acesso controlado por unidade</span></div></section>
 <footer className="app-footer"><span>* Os valores financeiros dependem da integração e não representam pagamentos verificados nesta fase.</span><span>Rede Mais Saúde · Central de Recuperação</span></footer></main></div></div>
}